services:
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
    command: ["--default_lua_flags=allow-undeclared-keys"]
    ports: [ "6379:6379" ]
    ulimits:
      memlock: -1
    restart: unless-stopped

  postgres:
    image: timescale/timescaledb:latest-pg16
    environment:
      POSTGRES_USER: rektrace
      POSTGRES_PASSWORD: rektrace
      POSTGRES_DB: rektrace
    ports: [ "5432:5432" ]
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data

  jaeger:
    image: jaegertracing/all-in-one:1.57
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686" # UI
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "14268:14268" # Jaeger HTTP collector (thrift)
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports: [ "3000:3000" ]
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_PASSWORD: grafana

  prom-metrics:
    build:
      context: .
      dockerfile: mcp/prom-metrics/Dockerfile
    profiles: ["mcp-custom"]
    restart: unless-stopped
    command: ["sleep", "infinity"]
    environment:
      - PROM_URL=http://prometheus:9090
    depends_on:
      prometheus:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "node -e 'process.exit(0)' "]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:


