version: '3.9'
services:
  app:
    build: .
    image: rektrace:latest
    environment:
      - HEALTH_PORT=8080
      - HTTP_ONLY=true
      - DEMO_MODE=true
    ports:
      - "8080:8080"
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  nginx:
    image: nginx:alpine
    volumes:
      - ./ops/nginx.example.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8443:443"
    depends_on:
      - app


