name: CI

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile
      - run: pnpm run build
      - run: pnpm run test
      - run: pnpm run perf:gate
      - run: pnpm run env:lint
        env:
          ENV_FILE: ./.env.prod
      - run: pnpm run preflight
      - run: |
          HTTP_ONLY=true DEMO_MODE=true HEALTH_PORT=0 pnpm rugscan:dev &
          sleep 2
      - run: pnpm run oracle:scan
      - run: pnpm run fuzz:scan
      - run: pnpm run chaos:smoke
      - run: bash scripts/sbom.sh
      - run: pkill -f "rektrace-rugscan/src/index.js" || true

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile
      - name: Build and bundle
        run: |
          VERSION=${GITHUB_REF_NAME#v} pnpm run release:bundle
          pnpm run release:checksum
          pnpm run perf:baseline
      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          files: |
            release_artifacts/*.tar.gz
            release_artifacts/**/FINGERPRINT.txt
            sbom.deps.json
            ops/baselines/*.json

name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install deps
        run: pnpm i --frozen-lockfile
      - name: Build
        run: pnpm run build && pnpm run rugscan:build
      - name: Tests
        run: pnpm run test
      - name: Typecheck
        run: pnpm run typecheck
      - name: Security Preflight
        run: pnpm run preflight
      - name: Start demo server
        run: HTTP_ONLY=true DEMO_MODE=true HEALTH_PORT=3010 pnpm rugscan:dev & sleep 2
      - name: Oracle check
        run: HOST=127.0.0.1 PORT=3010 bash scripts/oracle_scan.sh
      - name: Fuzz
        run: HOST=127.0.0.1 PORT=3010 bash scripts/fuzz_scan.sh
      - name: Chaos smoke
        run: HOST=127.0.0.1 PORT=3010 CHAOS_ENABLED=true bash scripts/chaos_smoke.sh
      - name: SBOM
        run: bash scripts/sbom.sh
      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-deps
          path: sbom.deps.json
      - name: Kill server
        if: always()
        run: pkill -f "tsx watch rektrace-rugscan/src/index.ts" || true
      - name: Abuse smoke
        run: pnpm run smoke:abuse


